sudo: required

services:
- docker

os:
- linux

language: go

go:
- 1.9

env:
  global:
  - HELM_URL=https://storage.googleapis.com/kubernetes-helm
  - HELM_TGZ=helm-v2.7.2-linux-amd64.tar.gz

before_install:
- wget -q ${HELM_URL}/${HELM_TGZ}
- tar xzfv ${HELM_TGZ}
- PATH=`pwd`/linux-amd64/:$PATH
- helm init --client-only

install:
- go get -t -v ./...

script:
- go test ./...
- make build-image

after_success:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- openssl aes-256-cbc -K $encrypted_4484f21cd8cd_key -iv $encrypted_4484f21cd8cd_iv -in .travis/kubeconfig.enc -out kubeconfig -d
- openssl aes-256-cbc -K $encrypted_4484f21cd8cd_key -iv $encrypted_4484f21cd8cd_iv -in .travis/bitcoin-exporter.yml.enc -out helm/bitcoin-exporter.yml -d
- if [ "$TRAVIS_BRANCH" == "master" ]; then make push-image && make KUBECONFIG=kubeconfig deploy; fi
