sudo: required

services:
- docker

os:
- linux

language: go

go:
- 1.9

env:
- KUBECONFIG=kubeconfig

before_install:
- openssl aes-256-cbc -K $encrypted_4484f21cd8cd_key -iv $encrypted_4484f21cd8cd_iv -in .travis/kubeconfig.enc -out $KUBECONFIG -d
- openssl aes-256-cbc -K $encrypted_4484f21cd8cd_key -iv $encrypted_4484f21cd8cd_iv -in .travis/bitcoin-exporter.yml.enc -out config/bitcoin-exporter.yml -d
- curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
- chmod +x ./kubectl
- sudo mv ./kubectl /usr/local/bin/kubectl

script:
- go test ./...

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
	make initial-deploy || make update-deploy
  fi
