apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: bitcoin-exporter-deployment
  labels:
    app: bitcoin-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoin-exporter
  template:
    metadata:
      labels:
        app: bitcoin-exporter
    spec:
      containers:
      - name: bitcoin-exporter
        image: justinbarrick/bitcoin-exporter:VERSION
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: bitcoin-exporter-config
          mountPath: /etc/bitcoin-exporter/
        args: ["/etc/bitcoin-exporter/bitcoin-exporter.yml"]
      volumes:
      - name: bitcoin-exporter-config
        configMap:
          name: bitcoin-exporter-config
---
kind: Service
apiVersion: v1
metadata:
  name: bitcoin-exporter
spec:
  selector:
    app: bitcoin-exporter
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
