version: '2.1'

services:
  build:
    build:
      context: ..
      dockerfile: docker/Dockerfile.build
    entrypoint: [ "go", "build", "cmd/bitcoin-exporter.go" ]
    volumes:
      - ..:/go/src/github.com/justinbarrick/bitcoin-exporter

  test:
    extends:
      service: build
    entrypoint: [ "go", "test", "./..." ]
