version: '2.1'

services:
  bitcoin-exporter:
    build:
      dockerfile: docker/Dockerfile
      context: ..
    command:
      - /app/bitcoin-exporter.yml
    volumes:
      - ../config/bitcoin-exporter.yml:/app/bitcoin-exporter.yml:ro

  prometheus:
    image: prom/prometheus
    volumes:
      - ../config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ../config/alerts/:/etc/prometheus/alerts/:ro
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ../config/alertmanager.yml:/etc/alertmanager/config.yml:ro
    command:
      - '-config.file=/etc/alertmanager/config.yml'

  grafana:
    image: grafana/grafana
    volumes:
      - ../config/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ../config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../config/nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - bitcoin-exporter
      - grafana
      - prometheus
      - alertmanager

volumes:
  prometheus:
