global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'bitcoin_exporter'

    static_configs:
      - targets: ['bitcoin-exporter:8080']

rule_files:
  - alerts/*.rules

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
